on: [push]

jobs:
  terraform_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkou@v2

      - uses: hashicorp/setup-terraform@v1

      - uses: dflook/terraform-fmt-check@v1
        with:
          path: tf/

